CompEvalProject_Django/mysite/books/urls.py
from django.urls import path
from . import views

# app 구분용 별칭, url의 일부로 사용됨
# namespace / prefix 
app_name = 'books'
urlpatterns = [
    # /books/
    path('', views.BooksModelView.as_view(), name='index'),
        #as.view는 객체를 만들어서 진행한다는 의미임
    # /books/book/
    path('book/', views.BookList.as_view(), name='book_list'),

    # /books/author/
    path('author/', views.AuthorList.as_view(), name='author_list'),

    # /books/publisher/
    path('publisher/', views.PublisherList.as_view(), name='publisher_list'),

    # /books/book/99/
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),

    # /books/author/99/
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name='author_detail'),

    # /books/publisher/99/
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name='publisher_detail'),
]

CompEvalProject_Django/mysite/myapp/urls.py
from django.urls import path
from . import views

app_name='myapp'

urlpatterns=[
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('ajaxreq/', views.ajaxRes, name='ajaxRes')
]

CompEvalProject_Django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from myapp import views
from evComp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),   
    path('books/', include('books.urls')),
    path('evComp/', include('evComp.urls')), 
]

CompEvalProject_Django/mysite/myapp/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

CompEvalProject_Django/mysite/myapp/views.py
from django.shortcuts import render
import json

# Create your views here.
from .models import Question, Choice

from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

# http://127.0.0.1:8000/myapp
def index(request):
    print("---------index()-------------")
    #QuerySet 타입의 객체로 반환
    latest_question_list = Question.objects.all().order_by('-pub_date')[:5]
    print(latest_question_list)
    context = {'latest_question_list': latest_question_list}
    return render(request, 'myapp/index.html', context)

# http://127.0.0.1:8000/myapp/2/
def detail(request, question_id):
    print("---------detail()------------- ", question_id)
    #Question 타입반환
    question = get_object_or_404(Question, pk=question_id)
    print("*** detail() : 변수 타입 ", type(question))#Question 
    print("*** detail() : 변수 값 ", question)#Question 객체의 __str__ 함수반환값    
    return render(request, 'myapp/detail.html', {'question' : question})

# http://127.0.0.1:8000/myapp/2/results/
def vote(request, question_id):
    print("---------vote()-------------")
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'myapp/detail.html', {'question':question, 'error_message' : '선택 불가입니다'})
    selected_choice.votes += 1
    selected_choice.save()
    # http://127.0.0.1:8000/myapp/2/results/
    return HttpResponseRedirect(reverse('myapp:results', args=(question.id,)))

# http://127.0.0.1:8000/myapp/2/results/
# 폼 데이터 처리 결과를 보여주는 로직
def results(request, question_id):
    print("---------results()-------------")
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'myapp/results.html', {'question':question})


#json 형태의 문자열로 응답 : 비동기
def ajaxRes(request):
    print("----- ajaxRes() -----")
    context = {'message': "비동기로 응답하는 데이터", 'age' : 20, 'like_count': 10, 'data':"['Task', 'Hours per Day'],['Work',     11],['Eat',      2],['Commute',  2],['Watch TV', 2],['Sleep',    7]"}
    return HttpResponse(json.dumps(context), content_type="application/json")



'''
* mysite/urls.py
    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', views.index, name='index'),
    path('myapp/<int:question_id>/', views.detail, name='detail'),
    path('myapp/<int:question_id>/results', views.results, name='results'),
    path('myapp/<int:question_id>/vote', views.vote, name='vote'),
]

'''

CompEvalProject_Django/mysite/myapp/templates/myapp/detail.html
<h1>detail.html</h1>

<hr>
<br>


<h3>{{question.question_text}}</h3>

{% if error_message %} <p><strong>{{error_message}}</strong></p>{% endif %}

<!-- <form action="/myapp/1/vote/" method="post"> -->
<form action="{% url 'myapp:vote' question.id %}" method="post">
    {% csrf_token %}    
    <!-- 
        1. Question과 Choice table의 관계 - 1:N
        2. xxx_set이란? 
            1:N 관계의 외래키로 연결된 N 테이블의 항목들을 활용하는 속성명        
    -->
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}" />
        <label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br />
    {% endfor %}

    <input type="submit" value="전송">
</form>



<!--
<form action="/myapp/1/vote/" method="post">
    <input type="hidden" name="csrfmiddlewaretoken" value="Kro5xmpXxgS0iQesOfchIEkqZeh2MIFnr7AFgbRcJbsrTXJHoWRoE79OLggqgibe">
    
    <input type="radio" name="choice" id="choice1" value="1" />
    <label for="choice1">사과</label><br />

    <input type="radio" name="choice" id="choice2" value="2" />
    <label for="choice2">배</label><br />

    <input type="radio" name="choice" id="choice3" value="3" />
    <label for="choice3">수박</label><br />
    

    <input type="submit" value="전송">
</form>
-->

CompEvalProject_Django/mysite/myapp/templates/myapp/index.html
<h1>index.html</h1>

<hr>
<br>

{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href='/myapp/{{question.id}}/'>{{question.question_text}}</a></li>
        {% endfor%}
    </ul>
{% else %}
    <p>myapp을 이용할 수 없음</p>
{% endif %}

<hr>
<h3>비동기 처리</h3>
<br>
<input type="button" class="like" name="master" value="비동기 test">
<p id="count"></p>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>


<script type="text/javascript">
  $(".like").click(function(){
    var pk = $(this).attr('name')
    $.ajax({ // .like 버튼을 클릭하면 <새로고침> 없이 ajax로 서버와 통신하겠다.
      type: "POST", // 데이터를 전송하는 방법을 지정
      url: "{% url 'myapp:ajaxRes' %}", // 통신할 url을 지정
      data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'}, // 서버로 데이터 전송시 옵션
      dataType: "json", // 서버측에서 전송한 데이터를 어떤 형식의 데이터로서 해석할 것인가를 지정, 없으면 알아서 판단
      // 서버측에서 전송한 Response 데이터 형식 (json)
      // {'likes_count': post.like_count, 'message': message }
      success: function(response){ // 통신 성공시 - 동적으로 좋아요 갯수 변경, 유저 목록 변경       
        $("#count").html(response.like_count+"개");   
        drawChart(response.data);
      },
      error: function(request, status, error){ // 통신 실패시 - 로그인 페이지 리다이렉트
        alert("비동기 요청 및 응답시 에러 발생")       
      },
    });
  })
    google.charts.load('current', {'packages':['corechart']});  
    function drawChart(v) {
                
        v = eval("["+v+"]")      
        
        var data = google.visualization.arrayToDataTable(v);

        var options = {
            title: 'My Daily Activities'
        };
        var chart = new google.visualization.PieChart(document.getElementById('piechart'));
        chart.draw(data, options);
    }
   
</script>

<div id="piechart" style="width: 900px; height: 500px;"></div>

CompEvalProject_Django/mysite/myapp/templates/myapp/results.html
<h1>results.html</h1>

<hr>
<br>


<h3>{{question.question_text}} </h3>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{choice.choice_text}} - {{choice.votes}} vote{{choice.votes | pluralize}}</li>
{% endfor %}
</ul>

<a href="{% url 'myapp:detail' question.id%}">상세 page로 이동</a>
<br>
<a href="{% url 'myapp:index'%}">index page로 이동</a>