CompEvalProject_Django/mysite/books/urls.py
from django.urls import path
from . import views

# app 구분용 별칭, url의 일부로 사용됨
# namespace / prefix 
app_name = 'books'
urlpatterns = [
    # /books/
    path('', views.BooksModelView.as_view(), name='index'),
        #as.view는 객체를 만들어서 진행한다는 의미임
    # /books/book/
    path('book/', views.BookList.as_view(), name='book_list'),

    # /books/author/
    path('author/', views.AuthorList.as_view(), name='author_list'),

    # /books/publisher/
    path('publisher/', views.PublisherList.as_view(), name='publisher_list'),

    # /books/book/99/
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),

    # /books/author/99/
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name='author_detail'),

    # /books/publisher/99/
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name='publisher_detail'),
]

CompEvalProject_Django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from myapp import views
from evComp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),   
    path('books/', include('books.urls')),
    path('evComp/', include('evComp.urls')), 
]

CompEvalProject_Django/mysite/books/models.py
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=100) # 음절 갯수(byte아님)

    # 책과 저자는 다대다 관계(N:M)
    authors = models.ManyToManyField('Author')

    # 책과 출판사는 N:1 관계(여러 권의 Book은 하나의 publisher간에 관계)
    # 출판사의 pk기준으로 참조하는 데이터는 해당 pk 삭제시 books tables에서도 삭제
    publisher = models.ForeignKey('Publisher', on_delete=models.CASCADE)

    publication_date = models.DateField()

    # book 객체값 출력시 자동 호출되는 함수
    def __str__(self):
        return self.title



class Author(models.Model):
    name = models.CharField(max_length=50)
    salutation = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    website = models.URLField()

    def __str__(self):
        return self.name

CompEvalProject_Django/mysite/books/views.py
from django.views.generic.base import TemplateView
from django.views.generic import ListView
from django.views.generic import DetailView
from books.models import Book, Author, Publisher


'''
http://ip:port/books
- 요청 받고 -> 화면 구성을 위한 list구성 -> 최종 template에게 출력 위힘
    : 요청박고 : http://ip:port/books
    : 화면 구성을 위한 list 구성
    context['model_list'] = ['Book', 'Author', 'Publisher']
    list에 선언된 순서대로 html에 보여짐
    향후에 순서 변경도 가능
    (화면 구성 + 응답지시)
    : 최종 template에게 출력 위힘
        화면 지정 : template_name = 'books/index.html
        실행 시점 : get_context_data() 함후가 return시 자동 실행

        - 결론 : http://ip:port/books -> BooksModelView -> index.html이 응답

1. class형 View
2. 별도의 처리 로직 없이 템플릿 파일만 출력(렌더링) 하고자 할 경우 구현 방법
    - TemplateView 상속
3. TemplateView를 상속한 경우
    1. template_name 
        - books 앱의 첫 화면 구성을 위한 템플릿 파일
    2. get_context_data()
        - 템플릿으로 전송해야 할 데이터가 있는 경우 재정의
        - super() 첫라인 필수
        - return 필수 
'''
class BooksModelView(TemplateView):
    # books/templates/books/index.html
    template_name = 'books/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print("**************************",context)
        # list 순서에 맞게 화면 구성, 순서 변경 가능
        context['model_list'] = ['Author', 'Publisher', 'Book']
        print("++++++++++++++++++++++++++", context)
        return context



# 각 table들의 모든 정보 제공하는 view + template
'''
1. ListView인 제네릭 view 상속
2. 객체가 들어 있는 리스트를 구성해서 이를 컨텍스트 변수로 템플릿에 전송만 하면 됨
    - table의 모든 데이터를 검색해서 전송하려 할 경우 모델명만 지정하면 됨
3. 자동 적용해주는 로직
    - templates 파일명 자동 반영
    - 모델명소문자_list.html
      : Book인 경우 book_list.html
      : books/book_list.html
'''
class BookList(ListView):
    model = Book 


class AuthorList(ListView):
    model = Author


class PublisherList(ListView):
    model = Publisher


# 조건 검색인경우 사용하는 제네릭 View 
''' 
1. DetailView 제네릭 상속
2. 기능 
    - 특정 객체 하나를 컨텍스트 변수에 담아서 템플릿 시스템에 전송
3. 처리 방식
    1. pk로 검색시 
        : table명 즉 모델명만 설정해주면 됨
        : URLconf에서 전송되는 데이터값을 기준으로 검색
    2. Template 명
        : 모델명소문자_detail.html로 자동 생성
''' 
class BookDetail(DetailView):
    model = Book


class AuthorDetail(DetailView):
    model = Author


class PublisherDetail(DetailView):
    model = Publisher

CompEvalProject_Django/mysite/books/templates/books/author_detail.html
{% extends "base_books.html" %}

{% block content %}

<h1>{{ object.name }}</h1>
<p>{{ object.salutation }}</p>
<li>Email: {{ object.email }}</li>

{% endblock content %}

CompEvalProject_Django/mysite/books/templates/books/author_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Author List</h2>
    <ul>
        {% for author in object_list %}
            <li><a href="{% url 'books:author_detail' author.id %}">{{ author.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

CompEvalProject_Django/mysite/books/templates/books/book_detail.html
{% extends "base_books.html" %}

{% block content %}

<h1>{{ object.title }}</h1>
<br>
<li>Authors: 
{% for author in object.authors.all %}

  {{ author }}
  {% if not forloop.last %},{% else %}{% endif %}
  
{% endfor %}
</li>

<li>Publisher: {{ object.publisher }}</li>
<li>Publication date: {{ object.publication_date }}</li>

{% endblock content %}

CompEvalProject_Django/mysite/books/templates/books/book_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Book List</h2>
    <ul>
        {% for book in object_list %}
            <li><a href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}

CompEvalProject_Django/mysite/books/templates/books/index.html
<!-- books 애플리케이션의 첫 화면 -->
{% extends "base.html" %}

<head>

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'books/style.css' %}">
<title>{% block title %}Books Application Site{% endblock %}</title>
</head>

<!--
--------------------------------------------------------------------------------------           
 예시
        <link rel="stylesheet" href="style.css">

        위의 link 태그는 stylesheet 와 관련이 있고,참조하는 파일은 style.css 이다라는 것!
 --------------------------------------------------------------------------------------
-->

<body>
    {% block content %}
        <h2>Books Management System</h2>
        <ul>
            {% for modelname in model_list %}

                {% with "books:"|add:modelname|lower|add:"_list" as urlvar %} <!--lower함수를 안 쓰는 방법은 books/urs.py에서 별칭을 Author로 하면 될 듯하다. -->
                    <!--
                        Author
                        books:"|add:modelname|lower|add:"_list
                        books : author_list로 변환
                        <li><a href="/books/author/">Author</a><li>-->
                    <li><a href="{% url urlvar %}">{{ modelname }}</a></li>
                
                {% endwith %}
        
            {% endfor %}
        
        </ul>
    {% endblock %}
</body>
 <!--
 with "books:"|add:modelname|lower|add:"_list" as urlvar 
 1. with : 변수에 값 대입하는 template 변수
 2. 변수 : urlvar
 3. "books:"|add:modelname|lower|add:"_list"
    - books
    - add : 결합 filter
    - lower : 소문자로 변환하는 filter
    - modelname : views.py로 부터 받은 data
    - add:modelname|lower
        : modelname 변수값을 소문자로 변환해서 결합하기
    - 결론
        books:소문자_list
4. <li><a href="/books/book/">Book</a></li> 
-->
            

CompEvalProject_Django/mysite/books/templates/books/publisher_detail.html
{% extends "base_books.html" %}

{% block content %}

<h1>{{ object.name }}</h1>
<p>{{ object.website }}</p>
<li>Address: {{ object.address }}</li>

{% endblock content %}

CompEvalProject_Django/mysite/books/templates/books/publisher_list.html
{% extends "base_books.html" %}

{% block content %}
    <h2>Publisher List</h2>
    <ul>
        {% for publisher in object_list %}
            <li><a href="{% url 'books:publisher_detail' publisher.id %}">{{ publisher.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}